/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Dictionary = IDL.Record({
  'sourceLanguage' : IDL.Text,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'favoriteWords' : IDL.Vec(IDL.Text),
  'targetLanguage' : IDL.Text,
  'wordPairs' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'unknownWords' : IDL.Vec(IDL.Text),
  'quizPosition' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const QuizQuestion = IDL.Record({
  'question' : IDL.Text,
  'correctAnswerIndex' : IDL.Nat,
  'options' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addWordPair' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkImportWordPairs' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createDictionary' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'getAllDictionaries' : IDL.Func([], [IDL.Vec(Dictionary)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDictionary' : IDL.Func([IDL.Text], [IDL.Opt(Dictionary)], ['query']),
  'getFavoriteQuizQuestion' : IDL.Func([IDL.Text], [IDL.Opt(QuizQuestion)], []),
  'getQuizQuestion' : IDL.Func([IDL.Text], [IDL.Opt(QuizQuestion)], []),
  'getUnknownQuizQuestion' : IDL.Func([IDL.Text], [IDL.Opt(QuizQuestion)], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markWordAsUnknown' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'removeWordFromUnknown' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'removeWordPair' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleFavoriteWord' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'updateWordPair' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Dictionary = IDL.Record({
    'sourceLanguage' : IDL.Text,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'favoriteWords' : IDL.Vec(IDL.Text),
    'targetLanguage' : IDL.Text,
    'wordPairs' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'unknownWords' : IDL.Vec(IDL.Text),
    'quizPosition' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const QuizQuestion = IDL.Record({
    'question' : IDL.Text,
    'correctAnswerIndex' : IDL.Nat,
    'options' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addWordPair' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkImportWordPairs' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createDictionary' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'getAllDictionaries' : IDL.Func([], [IDL.Vec(Dictionary)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDictionary' : IDL.Func([IDL.Text], [IDL.Opt(Dictionary)], ['query']),
    'getFavoriteQuizQuestion' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(QuizQuestion)],
        [],
      ),
    'getQuizQuestion' : IDL.Func([IDL.Text], [IDL.Opt(QuizQuestion)], []),
    'getUnknownQuizQuestion' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(QuizQuestion)],
        [],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markWordAsUnknown' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'removeWordFromUnknown' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'removeWordPair' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleFavoriteWord' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'updateWordPair' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };